### ISSUE TITLE
Similar functionality for transaction confirmation in online banking applications?

### ISSUE THREAD

**Issue by p-** [rsolomakhin/secure-payment-confirmation#38]
I'm sorry for this issue as it seems slightly off-topic.

As I understand Secure Payment Confirmation, its use cases lay in payments with credit cards or similar?
Are you aware of similar proposed features, that leverage WebAuthn to confirm transactions inside online banking applications?

E.g. PSD2 (via RTS) of the European Union has following requirements for transaction confirmation (with dynamic linking):

**RTS - Art 5 - Dynamic Linking**
> Where payment service providers apply strong customer authentication in accordance with Article 97(2) of Directive (EU) 2015/2366, in addition to the requirements of Article 4, they shall adopt security measures that meet each of the following requirements:
> (a)  **the payer is made aware of the amount of the payment transaction and of the payee**;
> (b)  **the authentication code generated shall be specific to the amount of the payment transaction and the payee agreed to by the payer when initiating the transaction**.
> (c)  **the authentication code accepted by the payment service provider corresponds to the original specific amount of the payment transaction and to the payee agreed to by the payer. Any change to the amount or the payee shall result in the invalidation of the authentication code generated**.
> For the purpose of paragraph 1, payment service providers shall adopt security measures which ensure the confidentiality, authenticity and integrity of each of the following:
> (a)  the amount of the transaction and the payee through all phases of authentication.
> (b)  the information displayed to the payer through all phases of authentication including generation, transmission and use of the authentication code.
> For the purpose of the requirement under point (b) in paragraph 1 and where payment service providers apply strong customer authentication in accordance with Article 97(2) of Directive (EU) 2015/2366 in relation to a card-based payment transaction for which the payer has given consent to the exact amount of the funds to be blocked pursuant to Article 75(1) of that Directive, the authentication code shall be specific to the amount that the payer has given consent to be blocked and agreed to by the payer when initiating the transaction.
> For the purpose of the requirement under point (b) in paragraph 1 and where payment service providers apply strong customer authentication in accordance with Article 97(2) of Directive (EU) 2015/2366 in relation to payment transactions for which the payer has given consent to execute a batch of remote electronic payment transactions to one or several payees, the authentication code shall be specific to the total amount of the batch of payment transactions and to the specified payees.

As I understand it, at least payee (e.g. account number) and amount would have to be displayed to the user inside an online banking application.

[Regulatory Technical Standard](https://www.eba.europa.eu/sites/default/documents/files/documents/10180/1761863/314bd4d5-ccad-47f8-bb11-84933e863944/Final%20draft%20RTS%20on%20SCA%20and%20CSC%20under%20PSD2%20%28EBA-RTS-2017-02%29.pdf)

**Comment by Goosth** [comment]
Hi Peter,

The Fido Alliance is doing a lot of work to ensure that they remain compliant with PSD2. They have written a white paper on the topic:

  *   https://fidoalliance.org/psd2-compliance/
This lists are a range of documents their dealing with Dynamic Linking (signing the transaction data, and displaying it and making sure that the two are the same).

I know there was originally an extension defined for transaction support in the WebAuthn API, but I believe that has been deprecated for Level 2 of WebAuthn, since no Authenticator implemented it. There was some concern raised on this in light of PSD2 Dynamic linking. I haven't followed up recently to see if there are other proposals on the table. We can also ask the W3C WebAuthn working group if they know.
Please share if you are aware of any, so that we could explore that further.

I'm very excited about the fact that SPC will (in my opinion) do a better job of WebAuthn for Payments, since the browser will actually do the display and signing of payment data in one activity. In fact, we might want to go and present SPC to the Fido Europe working group to get their input on it's ability to strengthen the alignment for PSD2.

Hope that helps.
Kind regards,
Gerhard

**Comment by ianbjacobs** [comment]
@p-,

We plan to discuss SPC with Open Banking further in a few weeks, building on this writeup from Chris Wood:
https://docs.google.com/document/d/1qjBPa6l0EM9A3sLl9neccq_8UPHe90jXTGXqcbge2vQ/edit

In the meantime, if you are satisfied we can close this general issue and then re-open more specific issues on SPC as it relates to Open Banking.

Thanks!

Ian

**Comment by p-** [comment]
Hi @Goosth and @ianbjacobs,

Thanks for the information!

>In the meantime, if you are satisfied we can close this general issue and then re-open more specific issues on SPC as it relates to Open Banking.

Agreed, I'll close this issue and will be following the discussions.
