### ISSUE TITLE
Support for A2A payments

### ISSUE THREAD

**Issue by cyberphone** [rsolomakhin/secure-payment-confirmation#50]
Note: this is a question for the coming spec, not the Stripe pilot.

I have not found any information on how SPC is supposed to deal with Account-to-Account payments like SEPA Instant.

A common characteristic of these systems is that they usually _do not come with a physical card_ (and associated printed account number), making it somewhat unclear how they fit a 3DS world.  Existing A2A payment systems do not require users to memorize or explicitly type account numbers.

**Comment by ianbjacobs** [comment]
Given previous discussions, I fully expect SPC to address a wide range of payment methods. See writeup on open banking for example [1].

Closing this issue since I believe our overall goal subsumes it.

[1] https://docs.google.com/document/d/1qjBPa6l0EM9A3sLl9neccq_8UPHe90jXTGXqcbge2vQ/edit#heading=h.xcy4pocdwypu
